import { Suspense } from 'react'
import './globals.css'
import Loading from '@/components/loading'
import NavBar from '@/components/navbar'
import FaleConosco from '@/components/faleConosco'
import Footer from '@/components/footer'

export const metadata = {
  title: 'Mesh Labs',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  // eslint-disable-next-line no-undef
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Suspense fallback={<Loading />}>
          <NavBar />
          {children}
          <FaleConosco />
          <Footer />
        </Suspense>
      </body>
    </html>
  )
}
